import { ArrowRight, BrainCircuit, CheckCircle2, Lightbulb, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const principles = [
  ["Diagnose before teaching", "Find prerequisite gaps before asking a learner to move forward.", BrainCircuit],
  ["Build understanding", "Move from visual and concrete ideas toward symbols and abstraction.", Lightbulb],
  ["Check the reasoning", "Look at intermediate steps—not only whether the final answer is correct.", CheckCircle2],
  ["Respond to misconceptions", "Use the kind of mistake a learner makes to choose the next explanation or hint.", Sparkles],
] as const;

export default function Landing() {
  return <div className="landing">
    <header className="landing-nav"><Link className="mihur-brand" to="/"><span>M</span>Mihur</Link><nav><a href="#how">How It Works</a><a href="#approach">Our Approach</a><a href="#parents">For Parents</a><a href="#about">About</a></nav><Link className="landing-signin" to="/login">Sign In</Link></header>
    <main>
      <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">PERSONALIZED MATHEMATICS LEARNING</p><h1>Math makes sense when it’s taught the way students learn.</h1><p className="hero-lede">Mihur helps students understand <em>why</em>, not just memorize <em>how</em>. It identifies learning gaps, adapts support, and guides learners from understanding to independent mastery.</p><div className="landing-actions"><Link className="cta-primary" to="/login">Start Learning <ArrowRight size={18}/></Link><a className="cta-secondary" href="#approach">See our approach</a></div><div className="trust-line"><ShieldCheck size={18}/> Curriculum-aligned · Misconception-aware · Step-by-step</div></div>
      <div className="reasoning-demo"><div className="demo-top"><span>See how Mihur teaches</span><span className="demo-pill">Algebra</span></div><p className="demo-label">Solve</p><div className="demo-math">3(x + 4) = 24</div><div className="student-step"><span>Your step</span><strong>3x + 4 = 24</strong></div><div className="mihur-response"><span className="response-mark">M</span><div><strong>You’re close. Look at the distribution.</strong><p>The 3 multiplies <em>both</em> terms inside the brackets.</p><div className="mini-math">3(x + 4) → 3x + 12</div><p className="question">Can you continue from here?</p></div></div></div></section>
      <section className="learning-path" id="how">{["See it","Understand it","Work it out","Explain it","Master it"].map((x,i)=><div key={x}><span>{i+1}</span><strong>{x}</strong>{i<4&&<ArrowRight className="path-arrow" size={18}/>}</div>)}</section>
      <section className="approach-section" id="approach"><div className="section-intro"><p className="eyebrow">OUR PEDAGOGICAL APPROACH</p><h2>We saw a gap in mathematics education.</h2><p>Students can complete assignments and memorize procedures while a small misunderstanding remains unresolved. Mathematics is cumulative. A gap in fractions, negative numbers, equivalence, or distribution can become a much larger obstacle later.</p><blockquote>Not simply “Did the student get the answer right?” but “What does the student understand, and where did the reasoning break down?”</blockquote></div><div className="principle-grid">{principles.map(([title,body,Icon])=><article className="principle-card" key={title}><Icon size={24}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="difference-section"><p className="eyebrow">THE MIHUR DIFFERENCE</p><h2>The difference isn’t more questions.<br/>It’s knowing what to do when a student struggles.</h2><p>Mihur uses hints and explanations to keep students thinking, then gives them opportunities to demonstrate the skill independently. Help is a bridge to mastery—not the finish line.</p></section>
      <section className="parents-section" id="parents"><div><p className="eyebrow">FOR PARENTS</p><h2>See progress without reading a technical log.</h2><p>Understand what your child is learning, where they are improving, and which concepts still need support.</p></div><div className="parent-points"><span>Learning progress</span><span>Mastery & retention</span><span>Concepts needing support</span><span>Curriculum-aligned activity</span></div></section>
      <section className="about-section" id="about"><p className="eyebrow">ABOUT MIHUR</p><h2>Built for understanding.</h2><p>Mihur began with a simple observation: students can spend a great deal of time practicing mathematics without resolving the misunderstanding holding them back. We are building a learning environment that combines strong mathematical pedagogy, curriculum alignment, adaptive practice, and carefully constrained AI to provide thoughtful individualized guidance at scale.</p><p><strong>Our goal is not to replace teachers.</strong> It is to give every learner more opportunities for individualized mathematical guidance between the moments when a teacher or parent can be beside them.</p></section>
    </main><footer className="landing-footer"><div className="mihur-brand"><span>M</span>Mihur</div><p>Understanding first. Mastery follows.</p><Link to="/login">Sign In</Link></footer>
  </div>;
}
